# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2791e0cb280a08b9bdf8e8b2c3b75179fc3945586ee5761bd4c10d75b4003c44c54c867cf0db9d5d9e9e88cef19d507edd2cccab0580d1909422742a4d9388ec

test:
  secret_key_base: aa96355a77e94b3b617b67c2db9650f3f5ea11bb1e4fdd08ee1c3226ed488fa10327a8dcb2a355926c2416e56ae0bb804ffc89b2ea877bcde083981c222b6fc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
